### ISSUE TITLE
 loss nan

### ISSUE THREAD

**Issue by kakaxi438** [suneric/coverage_path_planning#1]
我在运行ppo_train文件时会有loss为nan的情况，当代码运行到Episode:10的时候就会跳这样的
training Actor network...
epoch index 1 loss 12.516312599182129
epoch index 2 loss 12.50399398803711
epoch index 3 loss nan
epoch index 4 loss nan
epoch index 5 loss nan
epoch index 6 loss nan
epoch index 7 loss nan
最后就会报错。
Traceback (most recent call last):
  File "G:\SF\ppoljgh\coverage_path_planning\ppo_train.py", line 351, in <module>
    pred, act, val = agent.action(obs)
  File "G:\SF\ppoljgh\coverage_path_planning\ppo_train.py", line 253, in action
    act = np.random.choice(self.action_size,p=pred) # index of actions
  File "mtrand.pyx", line 928, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
当我把max_step改小，Episode就可以运行到更大的数字，到后面还是会跳上面这样的。只有将max_step改成0才能一直运行

**Comment by suneric** [comment]
You should be able to print the values of variables during loss evaluation and see what's going on.  Usually, nan loss issue is caused by gradient blow up.
